version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:etc/nginx/conf.d/default.conf
    depends_on:
      - web
